"""Copy the fixed-price proof artifact into a standalone publication checkout.

Run from the author's workspace with Python >= 3.11.  The source selection is
explicit; local Python imports and cited machine receipts extend that selection.
No searches or mathematical verification are run.  Existing destination files
outside this selection are preserved, so documentation can be edited separately.
"""

from __future__ import annotations

import argparse
import ast
from collections import Counter, defaultdict
import json
import os
from pathlib import Path
import re
import shutil
import stat
import sys
import tomllib


FP = Path("research_ideas/probes/fixed_price")
MANUSCRIPT = FP / "manuscript"
EXT = FP / "extension_screen_20260913"
CONT = EXT / "continuation"
MACHINE = {"lean", "exact", "arb", "sympy", "z3", "cvc5"}
SKIP_DIRS = {
    ".git", ".lake", ".deps", "__pycache__", "blueprints", "claude_replays",
    "discussion", "sources", "cw_repo", "reviews",
}

PYTHON_SEEDS = [
    FP / "calibration_probe.py",
    *[MANUSCRIPT / name for name in (
        "first_layer.py", "first_layer_register_20260913.py",
        "first_layer_20260921.py", "first_layer_repair_20260921.py",
        "verify_granularity_hard_20260918.py", "statement_correspondence.py",
        "checks/first_layer_20260921/max_convexity_exact.py",
        "checks/first_layer_repair_20260921/physical_conditions.py",
    )],
    *[EXT / name for name in (
        "shifted_algebra.py", "exact_witness.py", "continuum_to_finite.py",
    )],
    *[CONT / name for name in (
        "boundary_certificate.py", "branch_interval.py",
        "branch_interval_uniform.py", "branch_monotonicity.py",
        "branch_reduction.py", "endpoint_algebra.py",
        "outer_boundary_algebra.py", "polygon_witness.py",
        "stationary_branch_probe.py", "unified_principle/continuous_switching_exact.py",
        "general_dual/second_body_kernel.py", "buyer_adaptive_price/obstacle_components.py",
        "buyer_adaptive_price/prefix_components.py", "buyer_adaptive_price/step_dual_components.py",
    )],
]

# Inputs to retained construction helpers.  Floating discovery inputs are not
# proof credentials; their role is distinguished in PACKAGING.md.
INPUT_DATA = [
    *[EXT / "results" / name for name in (
        "source_best.json", "source_slsqp.json", "source_gurobi.json",
        "source_symmetric_slsqp.json", "free_support_refine_2.json",
        "euler_finite_64.json", "shifted_calibration_family.json",
    )],
    CONT / "results/outer_screen.json",
    CONT / "results/stationary_branch_uniform_arb.json",
]

ADDITIONAL_RECEIPTS = [
    *[MANUSCRIPT / "checks" / name for name in (
        "first_layer_v2.json", "first_layer_register_20260913.json",
        "register_displayed_steps_20260913.json",
        "granularity_hard_first_layer_20260918.json",
    )],
    CONT / "results/branch_elimination_algebra.json",
    CONT / "buyer_adaptive_price/prefix_components.json",
    CONT / "buyer_adaptive_price/step_dual_components.json",
]

OPTIONAL_PUBLIC_FILES = [
    *[MANUSCRIPT / "checks" / name for name in (
        "statement_correspondence.json", "statement_correspondence.md", "tex_statements.json",
    )],
    MANUSCRIPT / "formalization_supplement.tex",
    MANUSCRIPT / "formalization_supplement.pdf",
    MANUSCRIPT / "paper.aux",
]

OMISSIONS = [
    "The full manuscript TeX/PDF and its other build outputs; only the formalization supplement and paper.aux for its cross-references are selected.",
    "Unrelated research projects, discovery branches, source-paper PDFs, private prompts, agent conversations, and Rethlas proof-audit logs.",
    "Lean .lake caches, downloaded dependencies, junction targets, Python environments, optional Gurobi installation/license files, and generated bytecode.",
    "The full shared proof ledger; only fixed-price machine entries cited by the graph, Lean sources, and retained check programs are exported.",
]

RUNTIME_NOTES = [
    "Python >= 3.11 is required for tomllib. requirements.txt lists the packages used by the portable replay commands and imported helpers.",
    "The supported local replay is manuscript/first_layer_repair_20260921.py --run. It AST-loads the original mathematical functions and reads the filtered ledger. It writes two local receipt JSON files and does not edit the ledger or graph.",
    "manuscript/supplement/verify.py is unchanged and replays the finite witnesses and stored interval partitions; --fast skips its two interval-cover replays.",
    "The historical first_layer.py, first_layer_register_20260913.py, and first_layer_20260921.py main programs need unpublished manuscript TeX for source-location or byte-hash metadata. Their original source is retained; the repair driver reuses their mathematical functions without that metadata dependency.",
    "Some original constructors consult the ledger and return immediately when a receipt already exists. This is original lookup-first behavior, not a fresh replay. Use supplement/verify.py or the repair driver for reproduction.",
    "The legacy multiunit_screen.py module is included because exact_witness.py and continuum_to_finite.py import it. Its optional Gurobi search modes require gurobipy and a license; no published replay command uses those modes. Saved floating inputs are construction data, not universal proof evidence.",
    "cvxpy supports hz_certify.certificates' optional certificate-search functions; threadpoolctl is used by a retained legacy construction helper. They are included in requirements.txt even though the saved-certificate replay does not require a new optimization search.",
    "continuous_switching.py is retained only as the Reference helper imported by step_dual_components.py. Its numerical evaluations and step_dual_components.py's relaxed-energy output are discovery calculations, not machine proof credentials.",
    "Original source references and stored checksums are historical provenance. This packaging script adds no new content hashes, proof credentials, or verification gate.",
]


def linked(path: Path) -> bool:
    """Detect symlinks and Windows junctions before any directory traversal."""
    return path.is_symlink() or bool(
        getattr(path.lstat(), "st_file_attributes", 0)
        & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 1024)
    )


def walk_files(path: Path):
    for folder, dirs, files in os.walk(path, followlinks=False):
        base = Path(folder)
        dirs[:] = sorted(d for d in dirs if d not in SKIP_DIRS and not linked(base / d))
        for name in sorted(files):
            item = base / name
            if not linked(item):
                yield item


def text(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig")


def referenced_machine_keys(content: str, claims: dict) -> set[str]:
    # Ledger slugs are lower-case; several original Lean comments use theoremC.
    lowered = content.lower()
    return {
        key for key, value in claims.items()
        if key.lower() in lowered and MACHINE.intersection(value.get("verified", []))
        and (key.startswith(("fixed_price_", "fpm", "fp_"))
             or "fixed-price" in str(value.get("paper", "")).lower())
    }


def evidence_paths(record: dict):
    blob = json.dumps(record, ensure_ascii=False).replace("\\\\", "/").replace("\\", "/")
    pattern = r"(?:research_ideas/probes/fixed_price/|hz_certify/|proof_factgraph/)[A-Za-z0-9_./-]+\.(?:py|json|toml|lean)"
    for item in re.findall(pattern, blob):
        yield Path(item)


def filtered_ledger_bytes(raw: bytes, keys: set[str]) -> bytes:
    """Keep selected original entry bytes, including mixed historical newlines."""
    starts = list(re.finditer(rb"(?m)^\[claims\.([^\]\r\n]+)\]\r?$", raw))
    result = [
        b"# Fixed-price machine-evidence excerpt of the shared proof ledger.\n",
        b"# Selected records retain their original statements, scope, and evidence.\n",
        b"# This export is not a new verification run.\n\n",
    ]
    for i, match in enumerate(starts):
        if match.group(1).decode("utf-8") in keys:
            end = starts[i + 1].start() if i + 1 < len(starts) else len(raw)
            result.append(raw[match.start():end])
    content = b"".join(result)
    parsed = tomllib.loads(content.decode("utf-8"))
    if set(parsed["claims"]) != keys:
        raise ValueError("Could not preserve all selected ledger records")
    return content


def build(source: Path, destination: Path, defer_formalization: bool = False) -> dict:
    source = source.resolve()
    destination = destination.resolve()
    if destination == source or destination.is_relative_to(source / FP):
        raise ValueError("The publication directory must be distinct from the source tree")
    destination.mkdir(parents=True, exist_ok=True)
    selected: dict[Path, set[str]] = defaultdict(set)
    absent: list[str] = []

    def add(relative: Path, reason: str, optional: bool = False):
        relative = Path(relative)
        item = source / relative
        if not item.is_file():
            if optional:
                absent.append(relative.as_posix())
                return
            raise FileNotFoundError(item)
        if item.resolve() != item.absolute() or linked(item):
            raise ValueError(f"Selected source is a link or junction target: {item}")
        selected[relative].add(reason)

    lean_root = source / FP / "lean"
    lean_sources = [p for p in walk_files(lean_root) if p.suffix == ".lean"]
    for path in lean_sources:
        add(path.relative_to(source), "Lean source")
    for name in ("lakefile.toml", "lean-toolchain", "lake-manifest.json", ".gitignore"):
        add(FP / "lean" / name, "pinned Lean project configuration")
    add(FP / "lean/FixedPrice/TwoUnit/gen_data.py", "generator for the two finite Lean instances")
    for path in walk_files(source / MANUSCRIPT / "supplement"):
        if path.suffix in {".json", ".py", ".md"}:
            add(path.relative_to(source), "unaltered original supplement")
    for path in (source / "hz_certify").glob("*.py"):
        add(path.relative_to(source), "shared machine-check library")
    add(Path("hz_certify/README.md"), "shared machine-check library documentation")
    add(Path("proof_factgraph/factgraph.py"), "reader for the existing manuscript fact graph")
    add(MANUSCRIPT / "factgraph.toml", "manuscript fact graph")
    add(FP / "publication/prepare_artifact.py", "publication source selection")
    add(FP / ".gitattributes", "existing byte-preservation rule")
    for path in PYTHON_SEEDS:
        add(path, "manuscript machine-check program")
    for path in INPUT_DATA:
        add(path, "input to a retained construction helper", optional=True)
    for path in ADDITIONAL_RECEIPTS:
        add(path, "stored machine-check receipt")
    for folder in ("first_layer_20260921", "first_layer_repair_20260921"):
        for path in (source / MANUSCRIPT / "checks" / folder).glob("*.json"):
            add(path.relative_to(source), "stored machine-check receipt")
    for path in OPTIONAL_PUBLIC_FILES:
        if defer_formalization and path.name in {"formalization_supplement.tex", "formalization_supplement.pdf", "paper.aux"}:
            continue
        add(path, "public statement correspondence or formalization supplement", optional=True)

    module_index: dict[str, list[Path]] = defaultdict(list)
    for path in walk_files(source / FP):
        if path.suffix == ".py":
            module_index[path.stem].append(path.relative_to(source))
    external: dict[str, set[str]] = defaultdict(set)
    inspected: set[Path] = set()
    claims = tomllib.loads(text(source / "proof_factgraph/ledger.toml"))["claims"]
    initial_text = text(source / MANUSCRIPT / "factgraph.toml") + "\n" + "\n".join(map(text, lean_sources))
    keys = referenced_machine_keys(initial_text, claims)
    initial_count = len(keys)
    expanded_keys: set[str] = set()
    while True:
        before = (len(selected), len(keys))
        for relative in list(selected):
            if relative.suffix != ".py" or relative in inspected:
                continue
            inspected.add(relative)
            content = text(source / relative)
            keys.update(referenced_machine_keys(content, claims))
            tree = ast.parse(content, filename=str(relative))
            for node in ast.walk(tree):
                modules = ([a.name for a in node.names] if isinstance(node, ast.Import) else
                           [node.module] if isinstance(node, ast.ImportFrom) and node.module else [])
                for module in modules:
                    head = module.split(".")[0]
                    if head in sys.stdlib_module_names or head == "__future__":
                        continue
                    if head == "hz_certify":
                        continue
                    local = relative.parent / (module.replace(".", "/") + ".py")
                    if (source / local).is_file():
                        add(local, f"imported by {relative.as_posix()}")
                    else:
                        candidates = module_index.get(head, [])
                        if len(candidates) == 1:
                            add(candidates[0], f"imported by {relative.as_posix()}")
                        elif len(candidates) > 1:
                            raise ValueError(f"Ambiguous local import {module} in {relative}: {candidates}")
                        else:
                            external[head].add(relative.as_posix())
        for key in list(keys - expanded_keys):
            expanded_keys.add(key)
            record = claims[key]
            keys.update(referenced_machine_keys(json.dumps(record), claims))
            for path in evidence_paths(record):
                add(path, f"machine evidence cited by {key}")
        if before == (len(selected), len(keys)):
            break

    copied = []
    for relative in sorted(selected):
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source / relative, target)
        copied.append(relative.as_posix())
    # The only library-code adaptation: route optional ledger writes to this
    # checkout.  Original check formulas, source bytes, and receipts stay intact.
    ledger_module = destination / "hz_certify/ledger.py"
    original = ledger_module.read_bytes()
    old = b'LEDGER = Path(r"C:\\Users\\86131\\Documents\\proof_factgraph\\ledger.toml")'
    new = b'LEDGER = Path(__file__).resolve().parents[1] / "proof_factgraph" / "ledger.toml"'
    if original.count(old) != 1:
        raise ValueError("The known absolute ledger-path assignment has changed")
    ledger_module.write_bytes(original.replace(old, new))
    public_ledger = destination / "proof_factgraph/ledger.toml"
    public_ledger.write_bytes(filtered_ledger_bytes((source / "proof_factgraph/ledger.toml").read_bytes(), keys))
    (destination / "requirements.txt").write_text(
        "# Python >= 3.11\nsympy\npython-flint\nz3-solver\ncvc5\nnumpy\nscipy\nmpmath\ncvxpy\nthreadpoolctl\n",
        encoding="utf-8", newline="\n",
    )
    if not (destination / ".gitignore").exists():
        (destination / ".gitignore").write_text(
            "__pycache__/\n*.py[cod]\n.venv/\n.lake/\n*.olean\n*.ilean\n",
            encoding="utf-8", newline="\n",
        )
    if not (destination / ".gitattributes").exists():
        shutil.copyfile(source / FP / ".gitattributes", destination / ".gitattributes")

    report = {
        "copied_source_files": len(copied),
        "copied_bytes": sum((destination / p).stat().st_size for p in copied),
        "lean_source_files": len(lean_sources),
        "python_source_files": sum(Path(p).suffix == ".py" for p in copied),
        "initial_machine_ledger_entries": initial_count,
        "published_machine_ledger_entries": len(keys),
        "lean_ledger_entries": sum("lean" in claims[k].get("verified", []) for k in keys),
        "missing_optional_inputs_or_pending_public_files": sorted(set(absent)),
        "external_imports": {k: sorted(v) for k, v in sorted(external.items())},
    }
    lines = [
        "# Publication source selection", "",
        "This file documents packaging, not a new mathematical verification.", "",
        f"The selection contains {len(copied)} copied source/data files, including {len(lean_sources)} Lean files and {report['python_source_files']} Python files.",
        f"The filtered ledger has {len(keys)} machine entries, of which {report['lean_ledger_entries']} are Lean entries. {initial_count} entries are directly named by the manuscript graph or Lean sources; the remainder are referenced by retained programs or their evidence records.",
        "", "## Reproduction", "", "From the repository root:", "", "```sh",
        "python -m pip install -r requirements.txt",
        "python research_ideas/probes/fixed_price/manuscript/supplement/verify.py",
        "python research_ideas/probes/fixed_price/manuscript/first_layer_repair_20260921.py --run",
        "python research_ideas/probes/fixed_price/manuscript/checks/first_layer_20260921/max_convexity_exact.py",
        "python research_ideas/probes/fixed_price/manuscript/checks/first_layer_repair_20260921/physical_conditions.py",
        "```", "", "The Lean project retains its original pinned configuration:", "", "```sh",
        "cd research_ideas/probes/fixed_price/lean", "lake exe cache get", "lake build FixedPrice", "```", "",
        "## Portability and scope", "",
        "The only source adaptation is in `hz_certify/ledger.py`: its machine-specific absolute ledger path is replaced by `Path(__file__).resolve().parents[1] / 'proof_factgraph' / 'ledger.toml'`. The workspace original is unchanged.", "",
        *["- " + note for note in RUNTIME_NOTES], "", "## Omitted material", "",
        *["- " + note for note in OMISSIONS], "", "## Optional inputs absent at packaging time", "",
        *(["- `" + p + "`" for p in sorted(set(absent))] or ["None."]), "",
        "## Selection by source path", "",
        "All copied files retain the original relative paths. The ledger excerpt, requirements, root ignore/attribute rules, and this note are generated for the publication directory.", "",
        "| Source path | Reason |", "| --- | --- |",
    ]
    lines.extend(f"| `{p.as_posix()}` | {'; '.join(sorted(selected[p]))} |" for p in sorted(selected))
    lines.extend(["", "## Machine ledger entries", ""])
    lines.extend(f"- `{key}` ({', '.join(claims[key].get('verified', []))})" for key in sorted(keys))
    (destination / "PACKAGING.md").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, default=Path(__file__).resolve().parents[4])
    parser.add_argument("--destination", type=Path)
    parser.add_argument("--defer-formalization", action="store_true",
                        help="Leave the formalization supplement for a later authoring pass.")
    args = parser.parse_args()
    destination = args.destination or args.source_root / "fixed-price-bilateral-trade"
    print(json.dumps(build(args.source_root, destination, args.defer_formalization), indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
