"""Generate the Lean data modules for Theorem D from the supplement JSON files.

Sources (SHA-256 recorded in the generated files):
  manuscript/supplement/general_instance.json
  manuscript/supplement/symmetric_instance.json
Values and probabilities are scaled to natural numbers: general instance by the stored
value_denominator and probability_denominator; symmetric instance by the least common
denominators of its values and of its probabilities.
"""
import hashlib, json, math
from fractions import Fraction as F
from pathlib import Path

HERE = Path(__file__).resolve().parent
SUP = HERE.parents[2] / "manuscript" / "supplement"

def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()

def lean_list(name, rows):
    body = ",\n  ".join(f"(({a}, {b}), {w})" for (a, b), w in rows)
    return f"def {name} : List ((Nat × Nat) × Nat) := [\n  {body}]\n"

def write(path, header, parts):
    path.write_text(header + "\n".join(parts) + "\nend FixedPrice.TwoUnit\n", encoding="utf-8", newline="\n")

# general instance
gp = SUP / "general_instance.json"
g = json.loads(gp.read_text())
vd, pd = g["value_denominator"], g["probability_denominator"]
gb = [((v[0], v[1]), w) for v, w in g["buyers"]]
gs = [((v[0], v[1]), w) for v, w in g["sellers"]]
header = (f"/-! Generated by gen_data.py from manuscript/supplement/general_instance.json\n"
          f"(SHA-256 {sha(gp)}). Values are scaled by `generalValueDen = {vd}`,\n"
          f"probabilities by `generalProbDen = {pd}`. -/\n\nnamespace FixedPrice.TwoUnit\n\n")
write(HERE / "GeneralInstanceData.lean", header, [
    f"def generalValueDen : Nat := {vd}\n", f"def generalProbDen : Nat := {pd}\n",
    lean_list("generalBuyers", gb), lean_list("generalSellers", gs)])

# symmetric instance
sp = SUP / "symmetric_instance.json"
s = json.loads(sp.read_text())
rows_s = [(F(w), (F(a), F(c))) for w, (a, c) in s["seller_joint"]]
rows_b = [(F(w), (F(a), F(c))) for w, (a, c) in s["buyer_joint"]]
vden = 1
pden = 1
for w, (a, c) in rows_s + rows_b:
    vden = vden * a.denominator // math.gcd(vden, a.denominator)
    vden = vden * c.denominator // math.gcd(vden, c.denominator)
    pden = pden * w.denominator // math.gcd(pden, w.denominator)
assert sum(w for w, _ in rows_s) == 1 and sum(w for w, _ in rows_b) == 1
def scale(rows):
    out = []
    for w, (a, c) in rows:
        A, Cc, W = a * vden, c * vden, w * pden
        assert A.denominator == Cc.denominator == W.denominator == 1
        out.append(((A.numerator, Cc.numerator), W.numerator))
    return out
header = (f"/-! Generated by gen_data.py from manuscript/supplement/symmetric_instance.json\n"
          f"(SHA-256 {sha(sp)}). Values are scaled by `symmetricValueDen = {vden}`,\n"
          f"probabilities by `symmetricProbDen = {pden}`. -/\n\nnamespace FixedPrice.TwoUnit\n\n")
write(HERE / "SymmetricInstanceData.lean", header, [
    f"def symmetricValueDen : Nat := {vden}\n", f"def symmetricProbDen : Nat := {pden}\n",
    lean_list("symmetricBuyers", scale(rows_b)), lean_list("symmetricSellers", scale(rows_s))])
print("general", len(gb), len(gs), "symmetric", len(rows_b), len(rows_s), "vden", vden, "pden", pden)
